### ISSUE TITLE
Support for wildcards in handles

### ISSUE THREAD

**Issue by auer-kk** [namsral/multipass#5]
I would like to whitelist whole domains \*@tld or even anyone \*@\*. Would this be possible?

**Comment by namsral** [comment]
Not sure why you'd want to use Multipass when you accept any email address but matching whole domains is a sound idea. This enhancement can be added to the email handle service.

Example with a whole domain, wildcard subdomain and an email address:

```
multipass {
    handles domain.tld .domain.tld bob@domain.tld
    basepath /multipass
    mail_from "Multipass <no-reply@example.com>"
}
```

Handle classification:
- An email address when a handle contains an @ character
- A wildcard subdomain when a handle starts with a dot
- Otherwise a whole domain

**Comment by auer-kk** [comment]
"allow any" could come in handy, if there really are no restrictions or other restrictions like ipfilter apply. This would allow us to always use multipass (since handle is required) so there is only one way of access with centralized tracking/logging regardless of the actual context/scenario.

**Comment by namsral** [comment]
Commit 7972025a adds support for wildcard matches.

The pattern syntax is:
- 'bob@example.com' matches a single address
- '@example.com' matches any addresses with domain example.com
- '@' matches any address
